### ISSUE TITLE
接口测试GET, POST规范问题

### ISSUE THREAD

**Issue by Cherrison** [OhnkytaBlabdey/unichat-back-end#3]
使用POST是, 尽量使用`application/x-www-form-urlencoded`  
而不是放在Params 中

登录接口应该设计为POST而不是GET, 这样不安全, 比如在浏览器输入
`https://47.102.140.37:10010/signin?nickname=unichat&emailAddr=1111133u@dad.com&passwordHash=password`
就登录了, 而如果使用POST将信息放在form-data中就可以解决这个隐患

**Comment by OhnkytaBlabdey** [comment]
测试时只有浏览器，β阶段再关闭GET方法 🤣

**Comment by OhnkytaBlabdey** [comment]
已支持POST 表单 和 json 两种格式
